# Generated by Django 2.2 on 2020-10-01 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Departments',
            new_name='Department',
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.DegreeLevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.Department'),
            preserve_default=False,
        ),
    ]
