# Generated by Django 2.2 on 2021-01-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotlight', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
