# Generated by Django 2.2 on 2020-10-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=512)),
                ('mobile', models.CharField(max_length=12)),
                ('dob', models.DateField()),
                ('intro', models.CharField(blank=True, max_length=512, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('roll_number', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Skill')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Self-Employed', 'Self-Employed'), ('Freelance', 'Freelance'), ('Internship', 'Internship'), ('Trainee', 'Trainee')], max_length=15)),
                ('company', models.CharField(max_length=512)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('currently_working', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, max_length=512, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('date', models.DateField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentSkillEndorsement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('endorsed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentSkill')),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('relation', models.CharField(max_length=256)),
                ('given_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_by', to='student.Student')),
                ('given_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Language')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseEnrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CourseEnrollment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('attendance', models.BooleanField(default=True)),
                ('student_course_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentCourseEnrollment')),
            ],
        ),
    ]
